services:
  db:
    image: mysql:latest
    container_name: orders-python-db
    restart: unless-stopped
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'mysql_db'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
